services:
  global-disasters:
    image: global-disasters:${TAG}
    container_name: global-disasters
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8501:8501"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/global-disasters/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    environment:
      STREAMLIT_SERVER_PORT: 8501
      STREAMLIT_SERVER_ADDRESS: 0.0.0.0
      STREAMLIT_SERVER_HEADLESS: "true"
      STREAMLIT_SERVER_ENABLECORS: "false"
      STREAMLIT_SERVER_ENABLEXSRFPROTECTION: "false"
      STREAMLIT_SERVER_BASEURLPATH: global-disasters