services:
  em-view:
    container_name: global-disasters-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8501:8501"
    restart: unless-stopped
    volumes:
      - .:/app:cached
    environment:
      STREAMLIT_SERVER_PORT: 8501
      STREAMLIT_SERVER_HEADLESS: "true"
      STREAMLIT_SERVER_ENABLECORS: "false"
      STREAMLIT_SERVER_ENABLEXSRFPROTECTION: "false"
